### PR TITLE
add synchronization to LocalVariableTable

### PR DESCRIPTION
**Pull request by MrBagheera**
https://bugs.eclipse.org/bugs/show_bug.cgi?id=415838

### CODE REVIEW

**Comment by kriegaex** [comment]
Thanks for the contribution. Would you be able to create a test reproducing the problem and failing without, then passing with the patch?

**Comment by MrBagheera** [comment]
Yes, but since this error is related to concurrency, that necessarily would be a synthetic test - multiple threads performing legal sequence of method calls on single instance, with certain (high, but never 100%) chance of failing without patch. Of course after the fix i would always be passing. Does that work for you?

**Comment by kriegaex** [comment]
I am just giving you general advice. My more senior colleague @aclement will ultimately be the one to assess the quality and correctness of the patch, because I am not well versed in the internals of AspectJ yet. I am just trying to help and increase your chance of getting this patch in soon. Sorry that in Bugzilla it sat there without much subsequent action for such a long time.

IMO, whatever helps to reproduce the problem and set the stage for reviewing and evaluating this patch is helpful. If you can make your case more plausible by providing a test, even a heuristic one like the one you just described (I thought about the same scenario, BTW), you are increasing the chances to get this in.

**Comment by aclement** [comment]
@MrBagheera Yes, exactly, I think the test case would be somewhat synthetic. I'm actually interested in what else it might flush out. I'm not against the proposed changes but if anything I'm surprised concurrency issues arise just 'there', why not in the unpacking of other elements of the class too (LineNumberTable or whatever)? However, if we end up tackling `LocalVariableTable` here and then other locations as they come up, that's ok.

In principle each ClassLoader gets its own weaver instance but down in the depths there are these attempts to share what we can amongst instances. (e.g. `bootstrapTypes` in `LTWWorld` because why does everyone need their own copy of `java.lang.String`).

**Comment by BobKerns** [comment]
My original suggestion (back in 2013 before it was on github, so an attachment rather than a PR) did include LineNumberTable etc.
https://bugs.eclipse.org/bugs/attachment.cgi?id=234758&action=diff

Unfortunately, at this point, I do not even recall what my test framework was doing, let alone the details of my investigation. From my commentary, it would appear I tracked it to the lazy construction of these datastructures. It may be that it only hits LocalVariableTable due to the order of operations cause it to be more likely to fail there, but it seems inherently wrong to not synchronize these methods.

**Comment by kriegaex** [comment]
@aclement, please assign this to the 1.9.7 milestone. I am lacking the privileges to do so. You did not mention it explicitly in the release notes, so at least the search link would list it. Thank you very much.

**Comment by MrBagheera** [comment]
Thank you for accepting this pull request.

I managed to create the test to reproduce this issue - https://github.com/SmallGiantGames/org.aspectj/commit/c973566f543122c56b06b82fae4671dc880dc05f. On my machine with 10000 iterations test fails all the time, merging proposed fix makes it to pass.  

However, due to the nature of this test I'm a bit hesitant to include it into PR, so it is more for the demonstration that the problem was real.

**Comment by kriegaex** [comment]
@MrBagheera, the timing is a bit unfortunate. The PR is in the already released AspectJ 1.9.7, but the test comes after the fact. It still is very much welcome, though. Would you mind creating a separate PR on latest master, so we do not have to cherry-pick from your remote? On the new PR, we can comment on the test and improve it or merge it directly. I have not taken a closer look yet, because I hope that Andy shall do so. On the new PR, please also comment on typical test execution time on your hardware. Thank you. 🙂

**Comment by MrBagheera** [comment]
Added PR for the test - https://github.com/eclipse/org.aspectj/pull/77

**Pull request merged**
