### PR TITLE
Enable AJC compilation with `--release`

### PR DESCRIPTION
**Pull request by kriegaex**
Work in progress, relates to #70.

@aclement, please feel invited to contribute. Otherwise we could merge this (after I added an integration test), until we have a better idea or you have more time to implement it is a better way.

### CODE REVIEW

**Comment by aclement** [comment]
This doesn't feel quite right to me but I have no time to do anything better. With a test let's put it in.

**Comment by kriegaex** [comment]
> This doesn't feel quite right to me

I agree to some extent. That's why I want it in. 😉

Like I said, I am still counting on you to do it right, if you can join in my effort (or myself, once I feel more confident about understanding all that stuff well enough to do it right by myself). The idea is: Better a raw solution implementing (part of?) the feature in an unpolished way than an AJC which does it wrong all the time without any warnings. This way, at least we can see how stable it is and gather feedback from users about broken cases. Maybe this helps us craft a better solution. Also psychologically, I hope that having something in the product we do not feel comfortable with is a better incentive to improve it than simply not to touch this issue at all. I believe in continuous improvement.

**Comment by kriegaex** [comment]
@aclement, I added an integration test. It compiles a simple class which should contain a JDK 8 API call if `--release 8` works correctly. After compilation, directly inside the test method I use the existing BCEL infrastructure in order to inspect the byte code. First I had implemented the check directly in the compiled file using ASM, but adding both ASM and ASM tools to the classpath proved to be both tedious and more complicated than just adding some code to the test. Please review.

**Update:** I just rebased the code on master after you merged the two small PRs earlier today.

**Update 2:** OK, I verified that the test actually fails on GitHub CI when committing a test looking for the wrong disassembled output, see [CI build 228](https://github.com/eclipse/org.aspectj/actions/runs/973922446). I also checked that on Java 8 the test does not run, only on 9+ (11, 16 in our case). Now I have fixed and force-pushed again, the next build should pass normally.

**Update 3:** As expected, the new test passes on Java 11/16 now, see e.g. [build 229, Java 11](https://github.com/eclipse/org.aspectj/runs/2920544167?check_suite_focus=true#step:6:8508). On Java 8, it does not run, also as expected.

**Comment by aclement** [comment]
Yep, that's how I would have done the test too, nice. I was a bit surprised to see all that Java17 stuff in there though. I know we need it sometime, just didn't expect it here.

**Comment by kriegaex** [comment]
> I was a bit surprised to see all that Java17 stuff in there though. I know we need it sometime, just didn't expect it here.

In my defense: I had to put the new test somewhere, so I had to create the test directories, configs etc. for 1.9.8 anyway. There is no Java 17 test running yet, on Java 9-16 only this test runs. The others are just copy & paste and mostly empty shells. Only the sanity test would actually do something when running the build on Java 17. But as usual, it is just the same old test, only compiling to a (non-existent) Java 17 target. So it would fail now, because the compiler does not support level 17 yet, which is just what we expect for now.

If I would not have prepared the scaffolding, it would not have compiled or not run. It was enough work to update everything and not to overlook any version specifier. To delete the unnecessary stuff after copy & paste and then in a few weeks adding it again, would have been considerably more work.

**Pull request merged**
