### PR TITLE
Make asynchronous proceed thread-safe for nested around-advice

### LINKED ISSUE #128: Two Aspect Class,two around,get emptystack error
_Edited by @kriegaex_

When i use the code , i get the error（aspectj is 1.9.6）
```text
java.util.EmptyStackEcxeption
    at java.util.Stack.peek(Stack.java:102)
    at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:180)
    .....run()
```

However，i use 1.9.1，it is ok
I need help,thank you.

```java
@Aspect
@DeclarePrecedence(BB,AA)
public class AA{
    @Pointcut
    .....
    
    @Around
    public Object around(){
        Thread{
             point.proceed
        }
    }
}
```

```java
@Aspect
public class BB{
    @Pointcut
    .....
    
    @Around
    public Object around(){
             point.proceed
    }
}
```

### PR DESCRIPTION
**Pull request by kriegaex**
In case of asynchronous proceeding for nested around-advice, child threads need copies of the original around-closure stack. Otherwise, the target method thread will have popped the stack empty after unwinding. Therefore, the former simple `Stack<AroundClosure>` is now an `InheritableThreadLocal<Stack<AroundClosure>>` subclass which clones the stack for each new thread.

There also is a test based on a modified version of the sample code from https://github.com/eclipse/org.aspectj/issues/128#issuecomment-1050864557, verifying the following cases:

  1. outer around-aspect proceeds 1x, inner (asynchronous) around-aspect proceeds 1x,
  2. outer around-aspect proceeds 2x, inner (asynchronous) around-aspect proceeds 1x,
  3. outer around-aspect proceeds 1x, inner (asynchronous) around-aspect proceeds 2x,
  4. outer around-aspect proceeds 2x, inner (asynchronous) around-aspect proceeds 2x,

The main method producing the log output can be parametrised with two integer parameters, i.e. testing the behaviour with values of 5x outer, 7x inner is as easy as calling the same class with different parameters. Adding that test to the test suite is easy, too: Just add a new `<run ...>` section to _ajc198.xml_ and specify the expected set of (unordered) output lines.

This should fix all cases for child threads of the target joinpoint thread. There might be corner cases like someone proceeding in a runnable handed over to a thread pool of non-child threads. In that case, I think we would get into trouble, because the thread-local cannot inherit the stack from any parent thread and would be empty. I have no idea about the probability of the new code breaking existing AspectJ use cases in the field. Those however would already suffer from the problem that around-advice chains do not work correctly in multi-threaded situations, so I believe we would have heard complaints about that already and not only for the first time a few days ago in #128.

Fixes #128.
Supersedes #129.

### CODE REVIEW

**Comment by kriegaex** [comment]
> There might be corner cases like someone proceeding in a runnable handed over to a thread pool of non-child threads. In that case, I think we would get into trouble, because the thread-local cannot inherit the stack from any parent thread and would be empty.

Well, correctly expressing this situation, there is no notion of parent or child threads in Java, threads are just peers. What I really meant was:
  * Commit https://github.com/eclipse/org.aspectj/pull/132/commits/ab0d17d29fe65310a237bab72aa47606cab40cd4 fixes the usual situation that the proceeding thread is created from within an advice in the moment it is needed. Then it inherits the correct stack of closures, everything is fine.
  * The commit does **not** fix the situation that the executing thread has been created before, outside of the advice, e.g. as a thread pool member. If the advice in need of asynchronous execution simply hands over a runnable or callable to an executor service "owning" the thread pool, those previously created threads have no clue about the needs of aspects called later. The corresponding inheritable thread-locals will either contain an empty stack or whichever stack was created the first time an aspect triggered thread creation.

> I have no idea about the probability of the new code breaking existing AspectJ use cases in the field. Those however would already suffer from the problem that around-advice chains do not work correctly in multi-threaded situations, so I believe we would have heard complaints about that already and not only for the first time a few days ago in #128.

I am still supporting this statement. My local tests reproducing the executor thread problem also confirm that with the AspectJ 1.9.3 to 1.9.8 versions of `JoinPointImpl`, the stack exhaustion problems from #128 would also occur. I.e.,
  * this technical setup is not actively used out in the field, because it would not work,
  * we can merge this PR, because it fixes #128, but the solution does not cover thread pool situations, just like before. So it is a big improvement, but not perfect. @aclement, if you have any ideas how to also cover that case, I am all ears. I am going to think about it, but I would merge the PR even if we cannot come up with a solution (yet). We can always create an issue, so we do not forget it, and describe this limitation (which is as old as AspectJ itself) in the next release notes.

**Comment by kriegaex** [comment]
Besides, I have no idea how code-style aspects would behave in the same situations investigated and tested here. Do you happen to know, @aclement? Otherwise, I have to clone the tests and morph them into code-style equivalents.

**Update:** Code-style aspects work correctly in both cases. I have added more tests to the suite:

- [x] asynchronous proceed for nested around-advice (@AspectJ)
- [ ] asynchronous proceed for nested around-advice (@AspectJ, thread pool)
- [x] asynchronous proceed for nested around-advice (native)
- [x] asynchronous proceed for nested around-advice (native, thread pool)

I.e., only the 2nd scenario is failing with this PR. I am going to push the new tests, which should make one of them fail. Later we can decide if we want to ignore one test for now or if we have an idea how to the thread pool situation with code-style aspects, too. @aclement, I hope we can transfer some logic from code to annotation style. I guess, that logic does not live in the join point implementation in native AspectJ but the state is kept elsewhere. We would have to replicate that somehow. I have not looked into the code yet at all, so I am just speculating.

**Comment by kriegaex** [comment]
Yeah, case no. 2 (which also fails with any other AspectJ version) fails like I predicted. For the record (time stamps deleted):

```text
[ERROR] testAsyncProceedNestedAroundAdviceThreadPool_gh128(org.aspectj.systemtest.ajc198.Bugs198Tests)  Time elapsed: 0.89 s  <<< FAILURE!
junit.framework.AssertionFailedError: 

expecting output:
(...)
but found output:
(...)
java.util.EmptyStackException
  at java.base/java.util.Stack.peek(Stack.java:102)
  at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:182)
  at MarkerBAspect$1.run(MarkerBAspect.aj:19)
  at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
  at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
  at java.base/java.lang.Thread.run(Thread.java:829)

Expected 9 lines of output but there are 16
  at org.aspectj.systemtest.ajc198.Bugs198Tests.testAsyncProceedNestedAroundAdviceThreadPool_gh128(Bugs198Tests.java:56)
```

**Comment by kriegaex** [comment]
Hm, I am beginning to understand a bit more, but only have a little bit of time here and there to look into it without full focus. A main differences in how @AspectJ vs. native aspects are implemented seem to be that
  * native advice have an `AroundClosure` input parameter,
  * and therefore they can both receive and pass on around-closures, i.e. there is no need to keep an extra stack somewhere in the joinpoint instance,
  * as opposed to annotation-style advice which do not have that parameter, but instead have a `ProceedingJoinPoint` input parameter which the user can just call `proceed()` upon manually, either without any context parameters or only with an array of method arguments, but not with any around-closure information. Hence all the manual, error-prone book-keeping.

Without introducing a breaking change to require users to both declare and pass through around-closures - which is of course out of the question - we cannot easily emulate the pattern from native syntax  aspects. We have to leave it as-is or find a clever workaround how to transfer that context information.

image

**Comment by kriegaex** [comment]
@aclement, due to lack of feedback or code review, I would for now deactivate the one failing test and leave a TODO for the future, because I do not know how to fix that. Then I would merge this improvement and update the release notes. I am going to wait with that until tomorrow, though, just in case you wish to veto. I would actually feel better to merge this after a review, but also want to avoid to let this rot. If after my merge you think we have to revert or you want to commit improvements on top of it, then so be it.

**Comment by aclement** [comment]
Just merge it. As you say, we can revert if necessary.

**Pull request merged**
