### PR TITLE
Maven Central deployment

### PR DESCRIPTION
**Pull request by kriegaex**
This PR migrates (again, sorry) the deployment repositories for snapshots and releases, this time from AspectJ.dev to Sonatype OSSRH. This is also true for the ASM-renamed module, but I have not deployed the 9.1 release to Maven Central, it is still available on AspectJ.dev for now. I.e., AspectJ deployments go to Sonatype, but repositories to read from AspectJ.dev are still present in the parent POM, so ASM-renamed and JDT Core can still be read from there, until we finally decide how to handle those. Also, the new fork of AspectJ Maven Plugin is also not migrated to be deployed to Sonatype yet, so it also resided in AspectJ.dev for now. We need to keep things working during the transition.

Status quo:
  * Deployment to Sonatype OSSRH for all public artifacts: AspectJ matcher, runtime, weaver, tools - not installer (yet), because we disagree on whether it should be published on Maven Central or not.
  * Added automatic unzipping of source JARs and subsequent Javadoc generation for the artifacts mentioned above + ASM-renamed, active for Maven profile `release`.
  * Added automatic GPG signing for the artifacts mentioned above + ASM-renamed, active for Maven profile `release`.
  * Release from Maven without any manual extra steps is possible. I tested it like this:
    ```text
    mvn versions:set -DnewVersion=1.9.7-rc-1
    mvn -P release -DskipTests=true clean deploy
    ```
    This takes quite a while, because Javadoc generation is slow. But I successfully created staging repositories for AspectJ and ASM-renamed releases:
    ```text
    mvn -P release nexus-staging:rc-list

    [INFO] --- nexus-staging-maven-plugin:1.6.8:rc-list (default-cli) @ aspectj-parent ---
    [INFO]  + Using server credentials "ossrh" from Maven settings.
    [INFO]  * Connected to Nexus at https://oss.sonatype.org:443/, is version 2.14.20-02 and edition "Professional"
    [INFO] Getting list of available staging repositories...
    [INFO]
    [INFO] ID                   State    Description
    [INFO] orgaspectj-1091      CLOSED   org.aspectj:asm-renamed:9.1
    [INFO] orgaspectj-1101      CLOSED   org.aspectj:aspectjrt:1.9.7-rc-1
    ```

@aclement, you can log into Sonatype OSSRH Nexus with your own credentials and inspect the two staging repositories. Your feedback is welcome. Actually, I would like to promote the AspectJ 1.9.7-RC1 to Maven Central, then we can announce on the mailing list that something is available for testing, and a user also asked for it: https://github.com/eclipse/org.aspectj/issues/45#issuecomment-834088428

One more piece of information: Because Maven Javadoc plugin is quite JDK version sensitive, I made sure that Javadocs are created correctly when running Maven on JDK 16 first. Because of issue [OSSRH-66257](https://issues.sonatype.org/browse/OSSRH-66257), Nexus Staging plugin does need extra settings in order to successfully run on JDK 16:

```text
export MAVEN_OPTS="--add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.text=ALL-UNNAMED --add-opens=java.desktop/java.awt.font=ALL-UNNAMED"
```

I hope the plugin can be improved to not need this anymore in the future.

Because I also had problems, figuring out how to use Nexus Staging plugin for selectively deploying some, but not all multi-module project artifacts, I have created [OSSRH-68966](https://issues.sonatype.org/browse/OSSRH-68966). Please read, if you want to know what I tried and what failed until I arrived at the current solution.

### CODE REVIEW

**Comment by kriegaex** [comment]
**Update:** I also deployed a snapshot, because I had not checked that yet:

image

---

The release candidate staging repository looks like this:

image

---

image

**Comment by aclement** [comment]
I was thinking about attaching the installer to the release a bit like other projects do in github. For example, see this graal release where the release notes (which I might also like to capture in this way) include links to the downloads: https://github.com/graalvm/graalvm-ce-builds/releases/tag/vm-21.1.0 - maybe I've done this before for another project, maybe after creating the release you attach the artifact, can't quite remember though.

**Comment by aclement** [comment]
I manually merged the commit as it clashed for me (presumably because of the order I did the PRs in).

**Comment by kriegaex** [comment]
> I manually merged the commit as it clashed for me (presumably because of the order I did the PRs in).

That did not quite succeed. Please merge the new PR fixing it. Thank you.

**Comment by kriegaex** [comment]
BTW, it would be nice to have write access to the Eclipse repository. Then I could fix simple stuff like that without a PR.

**Comment by kriegaex** [comment]
> I was thinking about attaching the installer to the release a bit like other projects do in github.

This is similar to my idea to just push the installer to Maven Central whenever we release. Then it would be easy to refer to it, and there would be no vendor lock-in to GitHub for release availability. But for me, attaching it here is also fine if you prefer. How to do that, I am not sure. I would have to research first, too. Maybe it is necessary to do the release build with a GH workflow. Hopefully, we can also attach the release manually. But actually, I would prefer the automatic deployment solution during Maven release. It would come at no extra cost. I manually deactivated it in the POM, it was active before.

---

**Update:** See [Managing releases in a GitHub repository](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository). Again, only someone with write/admin access can do that, i.e. the burden is on you (also if e.g. I create a milestone release as discussed before). But it does not seem to be very difficult.

**Comment by aclement** [comment]
If you show me how other folks use maven central for those kinds of artifacts or mavens guidelines on this, that can persuade me, but I can't think of another time I've seen an installer non dependency in central - but as usual, I say I am not a maven guru.

**Comment by kriegaex** [comment]
> I can't think of another time I've seen an installer non dependency in central

You are right, I am wrong. My idea was just a bad one, born more out of a wish for simplicity than sense of reality or care for Maven Central conventions. I was just intrigued by the prospect of pushing out a binary distribution at the same time as deploying the main AspectJ Maven artifacts, because it would come for free with our build process. That something is easy does not necessarily mean that it is good, though. In this case it is actually bad.

I will not suggest this any longer. Thanks for discussing this with me for a few times, it helped convince me that I am wrong. 🙂

**Pull request merged**
