### PR TITLE
Trim trailing whitespaces.

### PR DESCRIPTION
**Pull request by turbanoff**
Trailing whitespaces are useless. Most of code-styles forbids them. Most of editors always trim them on save.
I propose to clean up project from trailing whitespaces in all java files at once.

### CODE REVIEW

**Comment by kriegaex** [comment]
I agree with you that trailing whitespace is useless. Since I started contributing here, I also cleaned up some files, usually when touching them anyway, changing something more substantial, according to the _boyscout rule_ to leave the camp ground behind a little cleaner than I found it. Sometimes I refrain from cleaning up whitespace, though, in order to have small commits and retain a more meaningful result of `git blame`. If whitespace was changed, I need to trace back to a previous ancestor commit in order to found out who really committed a certain piece of code and why. I wish that Git had a blame mode ignoring whitespace. Maybe it has and I simply do not know. Do you, @turbanoff?

**Comment by turbanoff** [comment]
I agree that _boyscout rule_ is a good way to reduce technical debt over time.
But often, such obvious "problems" make reviewers life harder - they generate noisy changes. For this one I believe it's better to pay this price once and forget about problem for a long time.

I use IntellIJ IDEA feature `Annotate` most often, instead of raw `git blame`. It ignores whitespaces by default
изображение
I believe it's possible with command line `git` too.
https://coderwall.com/p/x8xbnq/git-don-t-blame-people-for-changing-whitespaces-or-moving-code

**Comment by kriegaex** [comment]
> I use IntellIJ IDEA feature `Annotate` most often, instead of raw `git blame`. It ignores whitespaces by default

I use IDEA, too. I am going to double-check what you just said, thanks for the hint. 🙂 **Edit:** I just checked, you are right. Thanks!

image

> I believe it's possible with command line `git` too. https://coderwall.com/p/x8xbnq/git-don-t-blame-people-for-changing-whitespaces-or-moving-code

This looks promising, too. I am happy I asked and you replied.

**Comment by kriegaex** [comment]
General hint: Because AspectJ is an Eclipse project, you need to sign the [ECA (Eclipse Contributor Agreement)](https://www.eclipse.org/legal/ECA.php) first, see also the [ECA FAQ](https://www.eclipse.org/legal/ecafaq.php). I cannot merge PRs anyway, even if I wanted to (and I am not saying I do just yet). @aclement must do that for the time being, because I am still waiting for full committer status and the corresponding Eclipse and GitHub privileges.

Would you mind introducing yourself and explaining your sudden interest in AspectJ and burst of PRs?

**Comment by aclement** [comment]
I forget where we are on this but ideally we should have the formatting rules embedded in the project for the main IDEs to keep project consistency going forward.

**Comment by turbanoff** [comment]
Looks like it's already configured in `.editorconfig` to trim trailing whitespaces

https://github.com/eclipse/org.aspectj/blob/8b42ec9980b5a03c3d189156deb4b1212b26b793/.editorconfig#L20

It was just not applied to existing sources.

**Pull request merged**
