### PR TITLE
AspectJ 1.9.7 incl. JDT Core + test suite for Java 16

### PR DESCRIPTION
**Pull request by kriegaex**
Relates to and replaces #38.

* I think with regard to Java 15+16 language features, we are OK now, tests are also there. It was quite difficult to get the presets right so the test suite passes with all Java versions 8-16, always running and skipping the right tests.
* I also changed the JVM build test matrix in GitHub CI from [8, 11, 15] to [8, 11, 16], which is one of the reasons why I am opening this PR. I like to see the build feedback and find out if GitHub offers Java 16 already or not yet.
* I deactivated the `run-all-junit-tests` Maven module, see my e-mail. It almost doubles the build time because it runs all tests a second time which are normally run when building the corresponding modules. Still waiting for your feedback there, because I do not know if that module serves another, higher purpose and does something `mvn -test` does not do.
* I have refactored the way usage screens are printed: on stdOut now, no longer on stdErr, and for errors there is no more extra usage screen but the user can directly see the error(s).
* The resource bundle for the batch compiler messages has also been drastically shortened and is now a mere delta to Eclipse. This is still work in progress, I want to strip it down more.
* I fixed several tests which were failing passing on Linux (at least on GitHub) but failing on Windows or on machines with unexpected project base folder names.
* There are some other things, see the commit comments and my many e-mails (sorry for that, I hope you have time to read them).

### CODE REVIEW

**Comment by kriegaex** [comment]
Continuing our conversation from #38:

> I guess when I said 'commit on shadows' I was more generally talking about 'whatever the other end of this is' - so if it is something different that is of course fine but I think we need it in place at the same time as committing code into AspectJ that is based on it. So I guess I'm referring to this https://github.com/kriegaex/eclipse.jdt.core/tree/aj_19 that needs a proper home. I wasn't meaning to imply we have to tear it all down to shadows again. I am gradually falling out of the loop as you are finding way more cycles to move this forward than I am.

Thanks for the clarification. We are on the same page now. 😀

> Given that org.aspectj.shadows is still just a fake entry on GitHub, like AspectJ used to be, we can just park that for now. So we need a home for this ideally under eclipse/something but I feel it should have the AspectJ moniker in it to show what it is related to. Hmm `eclipse/aspectj.eclipse.jdt.core` - that's not tooo bad, if we renamed `eclipse/org.aspectj` to `eclipse/aspectj` at the same time for alignment maybe.

Sounds good to me. for now I have sent you invitations as a collaborator for both repositories,
  * my AspectJ clone and
  * my "new shadows" JDT Core clone.
I guess this means that you can commit code etc.

As for renaming to `eclipse/aspectj` or even better `eclipse/AspectJ` - I regularly use repo names with mixed case. I can also rename my JDT Core version and/or transfer ownership to you or Eclipse, if you can grant me full access there again after the transfer.

image

Of course the Eclipse organisation could also just fork my fork back into its own domain, whatever you or your admins think is right. There might be a problem with my commits, because I have not signed them off as I do with my AspectJ commits. I must have forgotten the setting, how ever I did that before.

**Comment by kriegaex** [comment]
> * I deactivated the `run-all-junit-tests` Maven module, see my e-mail. It almost doubles the build time because it runs all tests a second time which are normally run when building the corresponding modules. Still waiting for your feedback there, because I do not know if that module serves another, higher purpose and does something `mvn -test` does not do.

Average build times (for builds where at least one passed, i.e. ran until the end) is down from 31 to 17 minutes, which sounds to me like my changes pretty much did the job. I am still having this uneasy feeling that maybe someone might need that inactive module for something.

**Comment by aclement** [comment]
I will have to kick off some emails with the eclipse org about the repo renames and new repo creation. Having not signed off commits could well cause large amounts of pain in this process. I could also imagine the volume of the commit triggering some long review process with eclipse.

**Comment by kriegaex** [comment]
>Having not signed off commits could well cause large amounts of pain in this process.

I hate bureaucracy. The sign-off thing is just a line with my e-mail address in the commit comment AFAIK. I could of course edit the commits and force-push them (because the history would be rewritten, similar to a rebase). It would just eat some of my precious time and change the commit dates.

> I could also imagine the volume of the commit triggering some long review process with eclipse.

OMG, more bureaucracy? I thought you would be the reviewer and I told you so many details about what I did in my many e-mails.

**Comment by kriegaex** [comment]
> > Having not signed off commits could well cause large amounts of pain in this process.
> 
> I hate bureaucracy. The sign-off thing is just a line with my e-mail address in the commit comment AFAIK. I could of course edit the commits and force-push them (because the history would be rewritten, similar to a rebase). It would just eat some of my precious time and change the commit dates.

I wasted half a day in order to do that, using a history rewriting tool recommended in the Git manual itself, named [git-filter-repo](https://github.com/newren/git-filter-repo), which needs Python, so I had to install that first. From Git Bash I could first not use it and had to search the tool's FAQ for possible workarounds, none of which really worked for me as described, I had to adjust it a bit. Then I had to write my first Python script (I don't speak Python) in order to inject a call-back to modify my local history (only my own commits), which looks beautiful now. But when pushing the branch back to GitHub, I always end up with the old commits without signed-off messages. I even opened two issues, one for the tool and one directly at GitHub support. I lost a lot of time which could have been invested in real work on AspectJ or my actual job. This is why I hate bureaucracy so much: doing things which add zero value just because some inflexible rule requires it. What is this "signed-off" thing supposed to do anyway? It is not like the commit is really digitally signed using public-key cryptography. It is just a text line in the commit comment. I think this is stupid and just adds noise to the commit history. My name and e-mail address are already in the commit. Even if you accept my PR, I am still the author and you are the committer. I am so angry now that I even started trying this. Sorry for the rant.

Besides, I want to mention, just in case: I also refuse to play ping-pong in many iterations during a code review process in which some authority is micro-managing my required changes like I was a puppet on strings, like it happens in so many OSS project, scaring off potential contributors. This is a real anti-pattern and I pray that for (Eclipse) AspectJ it is different - at least it was until now, so that is positive. You accepted my PRs without much ceremony into the main repository. Why would it have to be different in our JDT Core clone?

Not entirely on topic and hopefully unrelated to AspectJ: It would not be the first PR I just gave up pushing because I do not like to spend more time in a review process talking about indentation, formatting, which methods should be private or protected and other details. A good reviewer guides me to fix bugs or serious shortcomings, but otherwise accepts the PR if it adds value, maybe in an incubation branch, fixing it up by herself like a good maintainer would, then integrating it into the master branch, telling me to inspect her fix-up commits, so I can learn something. This process would save both the reviewer and the contributor lots of time due to fewer iterations and context switched. Besides, all of this would be unnecessary when doing pair programming or at least some semblance of collaborative programming with short feedback cycles. (Yes, I am an agile coach in my daytime job and have been for almost 15 years.)

**Comment by cb4** [comment]
> * I deactivated the `run-all-junit-tests` Maven module, see my e-mail. It almost doubles the build time because it runs all tests a second time which are normally run when building the corresponding modules. Still waiting for your feedback there, because I do not know if that module serves another, higher purpose and does something `mvn -test` does not do.

Hi Alex - I will be working on AspectJ for PhD research over the next few months or so. Wondered why you reverted this one since I reached the same conclusion and also had removed it from my local copy. Thanks --Conrad

**Comment by kriegaex** [comment]
@cb4, see the next commit after the revert, please read the comment.

https://github.com/eclipse/org.aspectj/pull/39/commits/acdf4ffd9d4c6ee0b8d8595a112c5331974e08cb

**Comment by cb4** [comment]
> @cb4, see the next commit after the revert, please read the comment.
> 
Missed it the first time, so thanks for the pointer.

**Comment by s-jepsen** [comment]
Any idea, when version 1.9.7 will be released?

**Comment by kriegaex** [comment]
@s-jepsen, that is a good question. I cannot answer it with any confidence, only briefly explain what takes so long:
  * Presently, I am not an AspectJ committer, just a (first-time) contributor. So I cannot directly commit to the up-stream repository.
  * Maintainer @aclement is very busy with his daytime job as a Spring Engineering Director at VMware, trying to move Spring Boot Native on GraalVM forward, not having many free cycles to discuss, review commits and move processes within the Eclipse Foundation forward regarding my contributions.
  * Andy and I are in inconvenient time zones with regard to collaboration. He sits in Vancouver (-0700), I sit in South-East Asia (+0700). I.e. we lose a lot of time, because when he sleeps I work and vice versa.
  * In order to enable contributions via GitHub, some Git repositories have been or are in the process of being moved from Eclipse to GitHub. This takes time because it depends on internal Eclipse processes and availability of admins.
  * With regard to the AspectJ version of Eclipse JDT Core, I have started a new fork directly from upstream, enabling us to directly merge in new commits. In the past this was done doing manual patches. So here we have a whole new repository, retiring the legacy one at Eclipse. This took quite a while at Eclipse to set up for us here on GitHub.
  * Next, Andy could not accept my PR there for a long time due to some formalities around automatic contributor licence checks. This is too technical to go into detail, let's just say it cost us a lot of time.
  * My contributions are quite large, not just simple patches or bugfixes, so they might need extra internal reviews at Eclipse. (We are not sure about that yet.)
  * Without the JDT Core PR being accepted, Andy cannot accept the AspectJ PR either and much less perform a release, because the former is a dependency of the latter.
  * If both PRs have been accepted, theoretically we could do a release, but release notes have yet to be written. I also have not updated any other (developer) documentation with regard to my technical changes under the hood.
  * Besides, this PR is probably not the one which will be merged into AspectJ, because I have since then continued to work on some technical improvements with regard to build infrastructure, see #41. The latter is a superset of this one here.
  * Part of those technical changes was factoring out lots of dependencies from being committed in Git to fetching them from online sources. This also involves the AspectJ JDT Core I mentioned above. (Before, developers had to copy JDT Core from one local working directory into another, it was not mavenised.) In order to avoid more internal Eclipse processes and admin resource dependencies for now, I published them on GitHub Packages, not on Maven Central. This also needs to be reviewed and accepted by Eclipse.

Now that was just AspectJ incl. JDT Core.
* We also have AJDT (AspectJ Development Tools) for Eclipse IDE. Nobody has actively maintained it for years, Andy has maybe a day per year to keep it working in recent Eclipse versions and I have zero knowledge about Eclipse plugins in particular or OSGi bundles in general. Just yesterday, I managed to build AJDT with the new AspectJ in its belly and make it behave nicely on Eclipse 4.19 (2021-03). So that is another thing we need to push out for the benefit of developers using AspectJ + Eclipse IDE.
* I would also like to see a maintenance release of AspectJ Maven Plugin, which has been without an active maintainer on Mojohaus for years, which is why for Java 9+ everyone (including myself when upgrading AspectJ and AJDT) had to switch to Nick Wong's fork. Nick himself has also abandoned maintaining that fork, which means that I am going to fork it again, knowing nothing about Maven plugins. But I guess I can upgrade it to supporting Java 15/16. Subsequently, I am going to publish it under a new group ID. Then I have to convince both Eclipse and JetBrains to accept it as the "official" AspectJ Maven plugin for the future in order to make both IDEs automatically import projects using it. Eclipse still supports Mojohaus, IntelliJ IDEA at least knows about Nick's fork already.

After we get all of this done, we shall have a fairly up to date AspectJ ecosystem again.

**Comment by kriegaex** [comment]
This PR is superseded by #41.

**Pull request closed without merging**
