### PR TITLE
Fix merge from #52

### PR DESCRIPTION
**Pull request by kriegaex**
@aclement, you messed up the previous merge for #52 a bit. I fixed that and added another cosmetic commit. Please merge ASAP.

### CODE REVIEW

**Comment by aclement** [comment]
i had already started fixing it, so i merged the rest of your changes into mine.

**Comment by kriegaex** [comment]
What else was there to fix beside what I did?

**Comment by kriegaex** [comment]
Andy, you just should have accepted my PR or asked me for help with the merge or rebase before. Your fix is still incorrect:
  * Keep [this](https://github.com/eclipse/org.aspectj/blob/ca7cbda04dc3fd28e426570f3f766098ea6e8b3a/aspectjtools/pom.xml#L321-L324)
  * Delete [that](https://github.com/eclipse/org.aspectj/blob/ca7cbda04dc3fd28e426570f3f766098ea6e8b3a/aspectjtools/pom.xml#L345-L349)

**Comment by kriegaex** [comment]
> i had already started fixing it, so i merged the rest of your changes into mine.

Thank you. My "fix" removed one dependency too many anyway, namely `org.aspectj:asm`.

**Comment by kriegaex** [comment]
Argh, sorry, my bad. I had told you to remove it, but you were too fast and https://github.com/eclipse/org.aspectj/commit/9ba62b64fb2fd3a8b20d259189d392d9a4b30b72 should be reset and force-pushed or reverted. Sorry, sorry, sorry! Chat is better than this.

**Pull request closed without merging**
