### PR TITLE
AspectJ 1.9.7 incl. JDT Core + test suite for Java 15

### PR DESCRIPTION
**Pull request by kriegaex**
This is WIP (work in progress), but from my perspective we are pretty much done with the basic preparations for an AspectJ 1.9.7 release. For now we have
  * a Java 15 JDT core (created from https://github.com/kriegaex/eclipse.jdt.core/tree/aj_19),
  * Java 15 sanity tests,
  * [Java 15](https://openjdk.java.net/projects/jdk/15/) feature tests, e.g.
    * pattern matching for instanceof (second preview)
    * records (second preview)
    * sealed classes (preview)
    * hidden classes,
  * text blocks moved to full feature (non-preview) status.

@aclement, please feel free to comment and criticise. I can refine this PR as required or we can do it together.

FYI: One of the reasons I am opening the PR now is that I like to have the benefit of CI builds.

### CODE REVIEW

**Comment by aclement** [comment]
So is there a matching PR for org.aspectj.shadows to give alignment? (so the one introducing JDT 3caefb8021d710 ). Once that is incoming I'll merge them both together. This is an awesome bit of engineering involving a lot of archeology into processes, great stuff!  One thing we must do is update the wiki with all you've learned for anyone brave enough to follow in the foot steps.

**Comment by kriegaex** [comment]
Actually, I was hoping we could get rid of shadows in favour of my full JDT Core clone because it enables us to really make Git merges for everything except the `(TheOriginalJDT)?(Scanner|Parser)Class` stuff, which I did twice now - once for Java 15 and once for Java 16. I can make you or Eclipse owner of that fork. You could retire and set to read-only the existing shadows repository as a development history reference. We had talked about the idea of a real fork. You even said you would be interested in finding out if we can run the upstream JDT Core tests, which is a topic I have not looked into yet. I am a little bit disappointed now, because it was quite a lot of work to get everything working on the fork and my workstation, mostly because I did not have all the information I needed.

It would be possible to just copy everything manually to shadows, move the APT stuff to the extra subdirectory there and then just commit it, but in addition to updating jdtDepends I also changed the Ant build and the Eclipse project to search for APT where it is originally located in JDT Core. We would have to move it there first in a previous commit in order to make copy & paste even possible in the future. But actually, this is all additional work which I was hoping to avoid, especially future iterations. I will definitely keep doing the actual merge and development work in the JDT Core fork. Shadows is not a real Git fork, it is a manual copy of a subset of that project, which is what made merges so painful for you in the past in the first place.

**Comment by aclement** [comment]
I guess when I said 'commit on shadows' I was more generally talking about 'whatever the other end of this is' - so if it is something different that is of course fine but I think we need it in place at the same time as committing code into AspectJ that is based on it. So I guess I'm referring to this  https://github.com/kriegaex/eclipse.jdt.core/tree/aj_19 that needs a proper home. I wasn't meaning to imply we have to tear it all down to shadows again. I am gradually falling out of the loop as you are finding way more cycles to move this forward than I am.

**Comment by aclement** [comment]
Given that org.aspectj.shadows is still just a fake entry on GitHub, like AspectJ used to be, we can just park that for now. So we need a home for this ideally under eclipse/something but I feel it should have the AspectJ moniker in it to show what it is related to. Hmm `eclipse/aspectj.eclipse.jdt.core` - that's not tooo bad, if we renamed `eclipse/org.aspectj` to `eclipse/aspectj` at the same time for alignment maybe.

**Comment by kriegaex** [comment]
This one is obsolete, I opened a new PR for Java 15+16 and several more refactorings, it is a superset of this one.

**Pull request closed without merging**
