### PR TITLE
fix NPE when using LTW cache; fix TODO in SimpleCache#getAndInitialize

### LINKED ISSUE #285: NPE when using LTW cache
[ltw-npe-reproducer.zip](https://github.com/eclipse-aspectj/aspectj/files/14418122/ltw-npe-reproducer.zip)
step to reproduce: 
1. `unzip ltw-npe-reproducer.zip`  
2. `mvn clean package`  
3. `cd target; unzip ltw-npe-reproducer-1.0-SNAPSHOT-zip.zip`
4. `java -javaagent:aspectjweaver-1.9.21.1.jar -Daj.weaving.cache.enabled=true -Daj.weaving.cache.impl=shared  -cp ltw-npe-reproducer-1.0-SNAPSHOT.jar com.foo.bar.Demo`

### PR DESCRIPTION
**Pull request by KimmingLau**
1.write SAME_BYTES to cacheMap when wovenbytes is null  
 2.fix TODO in SimpleCache#getAndInitialize, use Optional to help indicating case in which Hit cache but need to return null

### CODE REVIEW

**Comment by kriegaex** [comment]
Why did close the issue? Your fix has neither been reviewed nor merged.

**Comment by kriegaex** [comment]
Why did you close the PR? Your fix has neither been reviewed nor merged.

**Comment by KimmingLau** [comment]
Sorry for that I found I missed a commit, and I've created an other PR

**Comment by kriegaex** [comment]
Oh sorry, I was confused, only briefly opening my messages on the road. 

Next time, please simply commit on top of the existing PR, or even force-push broken commits. No need to start over. 🙂

**Comment by KimmingLau** [comment]
Ok, I see

**Pull request closed without merging**
