### PR TITLE
Add release notes for 1.9.7

### PR DESCRIPTION
**Pull request by kriegaex**

### CODE REVIEW

**Comment by aclement** [comment]
The readme normally includes links to a bugzilla query for issues fixed in the release. That seems to be missing. On this occasion I'd probably include an additional link to a query showing fixes for the 1.9.7 tag in GitHub too.  If either of those tags is missing then we should remedy that.

**Comment by kriegaex** [comment]
I removed it on purpose for these reasons:
  * I checked the complete commit log between 1.9.6 and now when writing the release notes. Except for 1 or 2 commits by you, fixing minor things which I mentioned, there were before my time only CheckStyle-like refactorings by Lars.
  * I did not document any of my work in Bugzilla, and for most things I did, there are not GitHub tickets either. Instead, I described what we did in the release notes, making them one-stop shopping. I factored out the sample code into links instead.
  * I want to get rid of Bugzilla. I wish it was read-only already, so in the future people would create issues on GitHub.
  * Even if you would add a Bugzilla search link for 1.9.7, I doubt that it would yield any meaningful results.

So I do have my reasons for removing the link. Don't worry, the release notes are complete anyway, unless you take care of the two open PRs here and maybe a bunch of Bugzilla tickets you want in 1.9.7.

**Comment by aclement** [comment]
Now folks have to go and look for themselves to see what has been addressed, so we've added work for them. I'm talking about the general case, not the specific 1.9.7 case if we don't include these links, because I know 1.9.7 doesn't contain much explicit (which is also a negative point for us - we should be doing work/PRs against real issues). I found them useful, I find just summarizing issues in the text of the readme doesn't connect me back to the issue with all the context. I can think of many times I've recalled a bug, not sure precisely which one it was but located it through the queries in a readme.

**Comment by kriegaex** [comment]
> Now folks have to go and look for themselves to see what has been addressed

No, because the release notes I compiled are complete. Like I said, I created it by looking at the full list of commits since the last release. I would argue, this is what we always should do (in addition to linking to the issue tracker), because it can always happen that we have changes not covered by any GitHub issues.

> so we've added work for them

No, we save them work, because everything is in one place.

> I'm talking about the general case, not the specific 1.9.7 case

I did not say that in the general case we should not have this, but for 1.9.7 it is utterly useless IMO. Blame it on me that I did not create an issue for each PR, but most things I did for this release were not user-facing anyway. And if it was, I mentioned it in the release notes. I even mentioned the internal stuff, of course only at a high enough level so as not to bore users with it, but still attract potential contributors.

I agree that those lists were very helpful for previous releases and I am happy to see them back alive in the next release notes, if they prove to be more informative then. I am also OK with you having added them back, no problem at all if you want them in now in order to be able to more easily copy and paste the next time. They provide no extra value for 1.9.7, but they do not bother me either. 😊

**Comment by aclement** [comment]
When I create the queries, it actually makes me go and do a bit of housekeeping to see what I have in fact not closed but should be closed. There are now already a few closed for 1.9.7 that are on the list in the bugzilla query that I would otherwise have not tidied up. I suspect, because you know more about some of the changes around JDT, that others could also be closed as fixed in 1.9.7. Many of these I would never expect to be covered in the release notes directly, issues that require no code changes, issues that are dups of other issues. It doesn't make much of a dent in the huge backlog of issues, but it is something.

Can you comment on this one? https://bugs.eclipse.org/bugs/show_bug.cgi?id=559138 - it is fixed right?

And can you offer your input on: https://bugs.eclipse.org/bugs/show_bug.cgi?id=568800

**Comment by kriegaex** [comment]
> When I create the queries, it actually makes me go and do a bit of housekeeping to see what I have in fact not closed but should be closed.

Fair enough, that makes sense. Your way of working is different than mine, but just as valid. I am going to remember that and generally trying to remind myself to create more tracking tickets also for my own work in the future, especially when it is something affecting users. But I will keep up checking commit lists, too, so as not to miss anything.

As for Bugzilla, I guess you have a better overview there than I do, because you are always on CC when there is a new bug, I mostly monitor my own ones.

> Can you comment on this one? https://bugs.eclipse.org/bugs/show_bug.cgi?id=559138 - it is fixed right?
> 
> And can you offer your input on: https://bugs.eclipse.org/bugs/show_bug.cgi?id=568800

Will do.

**Pull request merged**
